version: "3.9"

services:
  lavinmq:
    image: cloudamqp/lavinmq:latest   # Docker Hub instead of GHCR
    container_name: lavinmq0
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./lavinmq-data:/var/lib/lavinmq

  robot-frontend:
    build:
      context: .
      dockerfile: robot-frontend/Dockerfile
    image: robot-frontend:latest
    container_name: robot-frontend
    restart: unless-stopped
    depends_on:
      - lavinmq
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./robot-config/message_broker_config.yaml:/app/config/message_broker_config.yaml:ro

  robot-backend:
    build:
      context: .
      dockerfile: robot-backend/Dockerfile
    image: robot-backend:latest
    container_name: robot-backend
    restart: unless-stopped
    depends_on:
      - lavinmq
    environment:
      - ROBOT_ID=r00
    volumes:
      - ./robot-config/message_broker_config.yaml:/app/config/message_broker_config.yaml:ro